name: Sync Sandbox with Master
on:
  push:
    branches:
      - "master"
jobs:
  sync-sandbox:
    name: sync-sandbox
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.TOKEN }}
          source: "master"
          target: "sandbox"
